languageCode = "en"
title = "Aerobatic Hugo Search Demo"

[params]

[[params.social]]
url = "https://github.com/aerobatic"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/aerobaticapp"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
